[package]
name = "cannon_wars"
version = "0.3.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
bevy = "0.9"
rand = "0.8"

[workspace]
resolver = "2" # Important! wgpu/Bevy needs this!
